### PR TITLE
email sending automation script added

### PR DESCRIPTION
**Pull request by UtkarshChaurasia**
This script automates the process of sending large number of emails.

### CODE REVIEW

**Review by sagnik20 — CHANGES_REQUESTED** [review]
Hey! this repo is made for complete beginners. Please add comment lines where ever necessary. :)

**Comment by UtkarshChaurasia** [comment]
@sagnik20 sure. Will add the comments.

**Comment by UtkarshChaurasia** [comment]
@sagnik20 comments have been added

**Review by sagnik20 — APPROVED** [review]
Thanks for your contribution. :)

**Pull request merged**
